sonar.projectKey=aptlogica_go-postgres-rest_3356bc40-4059-4939-8cce-5e86bba44a39

sonar.language=go
sonar.sources=pkg
sonar.tests=tests
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
