info:
  contact: {}
paths:
  /api/v1/schema/tables:
    get:
      parameters:
      - default: public
        description: Schema name
        in: query
        name: schema
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all tables
      tags:
      - tables
swagger: "2.0"
